Repository fga-eps-mds/2022-1-CAPJu-Doc, pull requests merged in 2022-08, with the labels that each got.

#130 Correção de Artefatos
  README.md
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/gerencia/atividades/atividades.md
  docs/gerencia/guia-de-contribuicao/guia-de-contribuicao.md
  docs/gerencia/sprints/sprint0.md
  docs/gerencia/sprints/sprint1.md
  docs/gerencia/sprints/sprint2.md
  docs/gerencia/sprints/sprint3.md
  docs/gerencia/sprints/sprint4.md
  docs/gerencia/sprints/sprint5.md
  docs/index.html
  docs/planejamento/eap.md
  docs/planejamento/planejamento-de-comunicacao.md
  docs/planejamento/planejamento-de-custo.md
  docs/planejamento/planejamento-de-qualidade.md
  docs/planejamento/planejamento-de-riscos.md
  docs/planejamento/planejamento-de-tempo.md
  docs/planejamento/treinamentos.md
  docs/projeto/prototipos.md
  docs/projeto/prototipos/alta.md
  docs/projeto/prototipos/baixa.md
  docs/projeto/quatro-de-conhecimentos.md
Labels: DOCS

#145 Criar formulário de validação - Sprint 2
  docs/testes-aceitacao/Testes Funcionais 1° Release-CAPJu - Formulários Google.pdf
Labels: EPS, atividade

#146 Criar formulário de validacao - Sprint 4
  docs/testes-aceitacao/Testes Funcionais 2ª Release-CAPJu - Formulários Google.pdf
Labels: EPS, ATIVIDADE

#147 Criar formulário de validação - Sprint 5
  docs/testes-aceitacao/Testes Funcionais 3ª Release-CAPJu - Formulários Google.pdf
Labels: EPS, ATIVIDADE
